In [ ]:
import numpy as np
import pandas as pd
import os



In [ ]:
# https://www.kaggle.com/datasets/usharengaraju/dynamically-generated-hate-speech-dataset
df1=pd.read_csv('./2020-12-31-DynamicallyGeneratedHateDataset-entries-v0.1.csv')


In [ ]:
df1.head(5)

Unnamed: 0     id                                               text label  \
0           1  10000  It should be legal for a husband to rape his wife  hate   
1           2  10001                            dalits are lowlife scum  hate   
2           3  10002                                dalits are lowlives  hate   
3           4  10003  It was a better world when women dare not ques...  hate   
4           5  10004  I don't work this hard so that those immigrant...  hate   

       type model_wrong  db.model_preds           status round  split  \
0  notgiven        True         0.97457  dynabench entry     1  train   
1  notgiven       False         0.08233  dynabench entry     1   test   
2  notgiven        True         0.92319  dynabench entry     1  train   
3  notgiven        True         0.99006  dynabench entry     1   test   
4  notgiven        True         0.98836  dynabench entry     1  train   

    annotator  
0  gnzuctwed3  
1  cagnluiznm  
2  cagnluiznm  
3  gnzuctwed3  
4  cagnluiznm

In [ ]:
df1["label"].replace({'hate': 1}, inplace=True)

In [ ]:
df1["label"].replace({'nothate': 0}, inplace=True)

In [ ]:
df1.drop(['id', 'type', 'model_wrong', 'db.model_preds', 'status', 'round', 'split', 'annotator'], axis=1)

Unnamed: 0                                               text  label
0               1  It should be legal for a husband to rape his wife      1
1               2                            dalits are lowlife scum      1
2               3                                dalits are lowlives      1
3               4  It was a better world when women dare not ques...      1
4               5  I don't work this hard so that those immigrant...      1
...           ...                                                ...    ...
40618       40736  we should forcibly remove all the foreigners f...      1
40619       40737  we should forcibly remove all the immigrants f...      1
40620       40738               dalits are unworthy of the Gods love      1
40621       40739                               dalits are worthless      1
40622       40740       dalits are deserves to be treated as lowlife      1

[40623 rows x 3 columns]

In [ ]:
df2=pd.read_csv('./labeled_data.csv')

In [ ]:
df2.head(5)

Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0           0      3            0                   0        3      2   
1           1      3            0                   3        0      1   
2           2      3            0                   3        0      1   
3           3      3            0                   2        1      1   
4           4      6            0                   6        0      1   

                                               tweet  
0  !!! RT @mayasolovely: As a woman you shouldn't...  
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...  
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...  
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...  
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [ ]:
df2.rename(columns = {'class':'label', 'tweet':'text'}, inplace = True)

In [ ]:
df2["label"].replace({0: 1}, inplace=True)

In [ ]:
df2["label"].replace({2: 0}, inplace=True)

In [ ]:
df2.head(5)

Unnamed: 0  count  hate_speech  offensive_language  neither  label  \
0           0      3            0                   0        3      0   
1           1      3            0                   3        0      1   
2           2      3            0                   3        0      1   
3           3      3            0                   2        1      1   
4           4      6            0                   6        0      1   

                                                text  
0  !!! RT @mayasolovely: As a woman you shouldn't...  
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...  
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...  
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...  
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [ ]:
df2.drop(['count', 'hate_speech', 'offensive_language', 'neither'], axis=1)

Unnamed: 0  label                                               text
0               0      0  !!! RT @mayasolovely: As a woman you shouldn't...
1               1      1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2               2      1  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3               3      1  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4               4      1  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...
...           ...    ...                                                ...
24778       25291      1  you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779       25292      0  you've gone and broke the wrong heart baby, an...
24780       25294      1  young buck wanna eat!!.. dat nigguh like I ain...
24781       25295      1              youu got wild bitches tellin you lies
24782       25296      0  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

[24783 rows x 3 columns]

In [ ]:
df2

Unnamed: 0  count  hate_speech  offensive_language  neither  label  \
0               0      3            0                   0        3      0   
1               1      3            0                   3        0      1   
2               2      3            0                   3        0      1   
3               3      3            0                   2        1      1   
4               4      6            0                   6        0      1   
...           ...    ...          ...                 ...      ...    ...   
24778       25291      3            0                   2        1      1   
24779       25292      3            0                   1        2      0   
24780       25294      3            0                   3        0      1   
24781       25295      6            0                   6        0      1   
24782       25296      3            0                   0        3      0   

                                                    text  
0      !!! RT @mayasolovely: As a woman you shouldn't...  
1      !!!!! RT @mleew17: boy dats cold...tyga dwn ba...  
2      !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...  
3      !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...  
4      !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...  
...                                                  ...  
24778  you's a muthaf***in lie &#8220;@LifeAsKing: @2...  
24779  you've gone and broke the wrong heart baby, an...  
24780  young buck wanna eat!!.. dat nigguh like I ain...  
24781              youu got wild bitches tellin you lies  
24782  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...  

[24783 rows x 7 columns]

In [ ]:
df=pd.concat([df1, df2])

In [ ]:
df.head(5)

Unnamed: 0     id                                               text  \
0           1  10000  It should be legal for a husband to rape his wife   
1           2  10001                            dalits are lowlife scum   
2           3  10002                                dalits are lowlives   
3           4  10003  It was a better world when women dare not ques...   
4           5  10004  I don't work this hard so that those immigrant...   

   label      type model_wrong  db.model_preds           status round  split  \
0      1  notgiven        True         0.97457  dynabench entry     1  train   
1      1  notgiven       False         0.08233  dynabench entry     1   test   
2      1  notgiven        True         0.92319  dynabench entry     1  train   
3      1  notgiven        True         0.99006  dynabench entry     1   test   
4      1  notgiven        True         0.98836  dynabench entry     1  train   

    annotator  count  hate_speech  offensive_language  neither  
0  gnzuctwed3    NaN          NaN                 NaN      NaN  
1  cagnluiznm    NaN          NaN                 NaN      NaN  
2  cagnluiznm    NaN          NaN                 NaN      NaN  
3  gnzuctwed3    NaN          NaN                 NaN      NaN  
4  cagnluiznm    NaN          NaN                 NaN      NaN

In [ ]:
df.shape

(65406, 15)

In [ ]:
import re
import nltk
nltk.download('stopwords')
stemmer = nltk.SnowballStemmer("english")
from nltk.corpus import stopwords
import string
stopword=set(stopwords.words('english'))


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
def clean_text(text):
    text = str(text).lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    text = [word for word in text.split(' ') if word not in stopword]
    text=" ".join(text)
    text = [stemmer.stem(word) for word in text.split(' ')]
    text=" ".join(text)
    return text

In [ ]:
df['text']=df['text'].apply(clean_text)

In [ ]:
df.head()

Unnamed: 0     id                                  text  label      type  \
0           1  10000               legal husband rape wife      1  notgiven   
1           2  10001                     dalit lowlif scum      1  notgiven   
2           3  10002                          dalit lowliv      1  notgiven   
3           4  10003  better world women dare question men      1  notgiven   
4           5  10004    dont work hard immigr take benefit      1  notgiven   

  model_wrong  db.model_preds           status round  split   annotator  \
0        True         0.97457  dynabench entry     1  train  gnzuctwed3   
1       False         0.08233  dynabench entry     1   test  cagnluiznm   
2        True         0.92319  dynabench entry     1  train  cagnluiznm   
3        True         0.99006  dynabench entry     1   test  gnzuctwed3   
4        True         0.98836  dynabench entry     1  train  cagnluiznm   

   count  hate_speech  offensive_language  neither  
0    NaN          NaN                 NaN      NaN  
1    NaN          NaN                 NaN      NaN  
2    NaN          NaN                 NaN      NaN  
3    NaN          NaN                 NaN      NaN  
4    NaN          NaN                 NaN      NaN

In [ ]:
from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt
import pandas as pd


In [ ]:
def make_wordcloud(df):
    comment_words=""
    for val in df.tweet:
        val = str(val).lower()


        comment_words += " ".join(val)+" "
    print(comment_words[0:100])
    wordcloud = WordCloud(width = 800, height = 800,
                background_color ='white',
                stopwords = stopwords,min_font_size = 10).generate(comment_words)

    plt.figure(figsize = (8, 8), facecolor = None)
    plt.imshow(wordcloud)
    plt.axis("off")
    plt.tight_layout(pad = 0)

    plt.show()

In [ ]:
# make_wordcloud(df[df['label']==0])

In [ ]:
x=df['text']
y=df['label']

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42)
print(len(x_train), len(y_train))
print(len(x_test), len(y_test))

49054 49054
16352 16352


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer(stop_words='english', ngram_range=(1,5))
x_train_vectorizer=count.fit_transform(x_train)

In [ ]:
x_test_vectorizer=count.transform(x_test)
x_train_vectorizer.toarray()


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
count.vocabulary_


{'worldwid': 839265,
 'median': 473382,
 'wealth': 809977,
 'black': 83169,
 'household': 344408,
 'deserv': 180138,
 'compar': 142387,
 'white': 815764,
 'worldwid median': 839280,
 'median wealth': 473383,
 'wealth black': 809983,
 'black household': 85082,
 'household deserv': 344420,
 'deserv compar': 180183,
 'compar white': 142580,
 'worldwid median wealth': 839281,
 'median wealth black': 473384,
 'wealth black household': 809984,
 'black household deserv': 85085,
 'household deserv compar': 344421,
 'deserv compar white': 180184,
 'worldwid median wealth black': 839282,
 'median wealth black household': 473385,
 'wealth black household deserv': 809987,
 'black household deserv compar': 85086,
 'household deserv compar white': 344422,
 'worldwid median wealth black household': 839283,
 'median wealth black household deserv': 473387,
 'wealth black household deserv compar': 809988,
 'black household deserv compar white': 85087,
 'lilaerii': 429571,
 'helloooo': 325217,
 'bitch': 

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf = TfidfTransformer()

x_train_tfidf = tfidf.fit_transform(x_train_vectorizer)

x_train_tfidf.toarray()
x_test_tfidf = tfidf.transform(x_test_vectorizer)


In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [ ]:
model_vectorizer= MultinomialNB().fit(x_train_vectorizer, y_train)
prediction_vectorizer=model_vectorizer.predict(x_test_vectorizer)
print(confusion_matrix(y_test,prediction_vectorizer))
print (classification_report(y_test, prediction_vectorizer))

[[1986 3546]
 [1746 9074]]
              precision    recall  f1-score   support

           0       0.53      0.36      0.43      5532
           1       0.72      0.84      0.77     10820

    accuracy                           0.68     16352
   macro avg       0.63      0.60      0.60     16352
weighted avg       0.66      0.68      0.66     16352



In [ ]:
model_tfidf= MultinomialNB().fit(x_train_tfidf, y_train)
prediction_tfidf=model_tfidf.predict(x_test_tfidf)
print (classification_report(y_test, prediction_tfidf))
print(confusion_matrix(y_test,prediction_tfidf))

              precision    recall  f1-score   support

           0       0.62      0.16      0.26      5532
           1       0.69      0.95      0.80     10820

    accuracy                           0.68     16352
   macro avg       0.65      0.56      0.53     16352
weighted avg       0.66      0.68      0.62     16352

[[  908  4624]
 [  564 10256]]


In [ ]:
import xgboost as xgb
xgb_model=xgb.XGBClassifier(
        learning_rate=0.1,
        max_depth=7,
        n_estimators=80,
        use_label_encoder=False,
        eval_metric='auc' )

/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")


In [ ]:
xgb_model_vectorizer = xgb_model.fit(x_train_vectorizer, y_train)
xgb_predictions_vectorizer=xgb_model_vectorizer.predict(x_test_vectorizer)
print(confusion_matrix(y_test,xgb_predictions_vectorizer))
print (classification_report(y_test, xgb_predictions_vectorizer))

[[4012 1520]
 [2447 8373]]
              precision    recall  f1-score   support

           0       0.62      0.73      0.67      5532
           1       0.85      0.77      0.81     10820

    accuracy                           0.76     16352
   macro avg       0.73      0.75      0.74     16352
weighted avg       0.77      0.76      0.76     16352



In [ ]:
xgb_model = xgb_model.fit(x_train_tfidf, y_train)
xgb_predictions=xgb_model.predict(x_test_tfidf)
print(confusion_matrix(y_test,xgb_predictions))
print (classification_report(y_test, xgb_predictions))

[[1941 3591]
 [ 944 9876]]
              precision    recall  f1-score   support

           0       0.67      0.35      0.46      5532
           1       0.73      0.91      0.81     10820

    accuracy                           0.72     16352
   macro avg       0.70      0.63      0.64     16352
weighted avg       0.71      0.72      0.69     16352



In [ ]:
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

In [ ]:
model1 = LogisticRegression(max_iter=1000)
model1.fit(x_train_vectorizer, y_train)


LogisticRegression(max_iter=1000)

In [ ]:
model2 = MultinomialNB()
model2.fit(x_train_vectorizer, y_train)

MultinomialNB()

In [ ]:
model3 = xgb.XGBClassifier()
model3.fit(x_train_vectorizer, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [ ]:
from sklearn.svm import LinearSVC
model4 = LinearSVC(max_iter=10000)
model4.fit(x_train_vectorizer, y_train)

LinearSVC(max_iter=10000)

In [ ]:
# Create the ensemble model
ensemble_model = VotingClassifier(estimators=[('lr', model1), ('nb', model2), ('gbm', model3), ('svc', model4)], voting='hard')
ensemble_model.fit(x_train_vectorizer, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression(max_iter=1000)),
                             ('nb', MultinomialNB()),
                             ('gbm',
                              XGBClassifier(base_score=None, booster=None,
                                            callbacks=None,
                                            colsample_bylevel=None,
                                            colsample_bynode=None,
                                            colsample_bytree=None,
                                            early_stopping_rounds=None,
                                            enable_categorical=False,
                                            eval_metric=None,
                                            feature_types=None, gamma=None,
                                            gpu_id=None, grow_policy=None,
                                            importance_type=None,
                                            interaction_constraints=None,
                                            learning_rate=None, max_bin=None,
                                            max_cat_threshold=None,
                                            max_cat_to_onehot=None,
                                            max_delta_step=None, max_depth=None,
                                            max_leaves=None,
                                            min_child_weight=None, missing=nan,
                                            monotone_constraints=None,
                                            n_estimators=100, n_jobs=None,
                                            num_parallel_tree=None,
                                            predictor=None, random_state=None, ...)),
                             ('svc', LinearSVC(max_iter=10000))])

In [ ]:
ensemble_model_predictions=ensemble_model.predict(x_test_vectorizer)
print(confusion_matrix(y_test,ensemble_model_predictions))
print (classification_report(y_test, ensemble_model_predictions))
accuracy = accuracy_score(y_test, ensemble_model_predictions)

# Print the accuracy
print("Accuracy:", accuracy)

[[3915 1617]
 [1908 8912]]
              precision    recall  f1-score   support

           0       0.67      0.71      0.69      5532
           1       0.85      0.82      0.83     10820

    accuracy                           0.78     16352
   macro avg       0.76      0.77      0.76     16352
weighted avg       0.79      0.78      0.79     16352



NameError: ignored

In [ ]:
from keras.models import Model
from keras.layers import LSTM, Activation, Dense, Dropout, Input, Embedding,SpatialDropout1D
from keras.optimizers import RMSprop
from keras.preprocessing.text import Tokenizer
from keras.preprocessing import sequence
from keras.utils import to_categorical
from keras.callbacks import EarlyStopping
from keras.models import Sequential
from keras.utils import pad_sequences


In [ ]:
max_words = 50000
max_len = 300
tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(x_train)
sequences = tokenizer.texts_to_sequences(x_train)
sequences_matrix = pad_sequences(sequences,maxlen=max_len)

In [ ]:
model = Sequential()
model.add(Embedding(max_words, 100, input_length=max_len))
model.add(SpatialDropout1D(0.2))
model.add(LSTM(100, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid'))
model.summary()
model.compile(loss='binary_crossentropy',optimizer=RMSprop(),metrics=['accuracy'])

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 300, 100)          5000000   
                                                                 
 spatial_dropout1d (SpatialD  (None, 300, 100)         0         
 ropout1D)                                                       
                                                                 
 lstm (LSTM)                 (None, 100)               80400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 5,080,501
Trainable params: 5,080,501
Non-trainable params: 0
_________________________________________________________________


In [ ]:
from keras.callbacks import EarlyStopping,ModelCheckpoint

stop = EarlyStopping(
    monitor='val_accuracy',
    mode='max',
    patience=5
)

checkpoint= ModelCheckpoint(
    filepath='./',
    save_weights_only=True,
    monitor='val_accuracy',
    mode='max',
    save_best_only=True)

In [ ]:
history=model.fit(sequences_matrix,y_train,batch_size=1024,epochs=10,
          validation_split=0.2,callbacks=[stop,checkpoint])

Epoch 1/10
39/39 [==============================] - 57s 1s/step - loss: 0.6147 - accuracy: 0.6555 - val_loss: 0.5185 - val_accuracy: 0.7224
Epoch 2/10
39/39 [==============================] - 56s 1s/step - loss: 0.4613 - accuracy: 0.7671 - val_loss: 0.4499 - val_accuracy: 0.7728
Epoch 3/10
39/39 [==============================] - 54s 1s/step - loss: 0.4017 - accuracy: 0.8104 - val_loss: 0.4400 - val_accuracy: 0.7845
Epoch 4/10
39/39 [==============================] - 53s 1s/step - loss: 0.3717 - accuracy: 0.8298 - val_loss: 0.4372 - val_accuracy: 0.7893
Epoch 5/10
39/39 [==============================] - 52s 1s/step - loss: 0.3519 - accuracy: 0.8397 - val_loss: 0.4298 - val_accuracy: 0.7951
Epoch 6/10
39/39 [==============================] - 57s 1s/step - loss: 0.3367 - accuracy: 0.8491 - val_loss: 0.4339 - val_accuracy: 0.7930
Epoch 7/10
39/39 [==============================] - 57s 1s/step - loss: 0.3216 - accuracy: 0.8567 - val_loss: 0.4427 - val_accuracy: 0.7942
Epoch 8/10
39/39 [==

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
test_sequences = tokenizer.texts_to_sequences(x_test)
test_sequences_matrix = pad_sequences(test_sequences,maxlen=max_len)

In [ ]:
accr = model.evaluate(test_sequences_matrix,y_test)

511/511 [==============================] - 50s 98ms/step - loss: 0.4754 - accuracy: 0.7882


In [ ]:
lstm_prediction=model.predict(test_sequences_matrix)


511/511 [==============================] - 45s 87ms/step


In [ ]:
res=[]
for prediction in lstm_prediction:
    if prediction[0]<0.5:
        res.append(0)
    else:
        res.append(1)

In [ ]:
print(confusion_matrix(y_test,res))


[[3783 1749]
 [1715 9105]]


In [ ]:
import pickle
with open('tokenizer.pickle', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)

NameError: ignored

In [ ]:
model.save("/content/drive/MyDrive/SavedModels/hate_speech_model_binary.h5")

In [ ]:
import keras

In [ ]:
load_model=keras.models.load_model("/content/drive/MyDrive/SavedModels/hate_speech_model_binary.h5")
with open('tokenizer.pickle', 'rb') as handle:
    load_tokenizer = pickle.load(handle)

EOFError: ignored

In [ ]:
test = input("Enter test sentence: ")


def clean_text(text):
    print(text)
    text = str(text).lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    print(text)
    text = [word for word in text.split(' ') if word not in stopword]
    text=" ".join(text)
    text = [stemmer.stem(word) for word in text.split(' ')]
    text=" ".join(text)
    return text
test=[clean_text(test)]
print(test)
seq = load_tokenizer.texts_to_sequences(test)
padded = pad_sequences(seq, maxlen=300)
print(seq)
pred = load_model.predict(padded)
print("pred", pred)
if pred<0.5:
    print("no hate")
else:
    print("hate and abusive")

Enter test sentence: hello world
hello world
hello world
['hello world']
[[2141, 54]]
1/1 [==============================] - 0s 94ms/step
pred [[0.11857848]]
no hate
